### ISSUE TITLE
Decoding Text Embeddings Coded Using Hugging Face ClipTextModel

### ISSUE THREAD

**Issue by mbdzi** [fkodom/clip-text-decoder#10]
Suppose that I have text embeddings created using Hugging Face's [ClipTextModel ](https://huggingface.co/docs/transformers/model_doc/clip#transformers.CLIPTextModel) using the following method:

```
import torch
from transformers import CLIPTokenizer, CLIPTextModel

class_list = ["i love going home and playing with my wife and kids", "i love going home", "playing with my wife and kids", 
"family", "war", "writing"]

model = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14")
tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")

inputs = tokenizer(class_list, padding=True, return_tensors="pt")
outputs = model(**inputs)
hidden_state = outputs.last_hidden_state
embeddings = outputs.pooler_output
```

Questions:

1. Is It possible to use the clip-text-decoder to convert the embeddings back to text?
2. If it is indeed possible to do so, could you provide an example of how?

Looking forward to receiving your feedback.

**Comment by Adenialzz** [comment]
Maybe you can train clip-text-decoder with a clip image encoder and try so. I am also going to do this.

**Comment by fkodom** [comment]
@mbdzi I believe @Adenialzz is correct. The pretrained model in `clip_text_decoder` likely won't work out-of-the-box, since the CLIP image/text embeddings likely don't line up closely enough.  But it should be possible to train a new model on the text encodings dataset. 

^^ I've been meaning to add clearer documentation around custom training.  Might not have time until later this week, but let me know if you have any questions in the meantime 👍

**Comment by Adenialzz** [comment]
@fkodom @mbdzi Extracting text features with the clip text encoder and reconstructing with the text decoder yielded plausible-looking results. Note that the text decoder is trained by the corresponding clip image encoder. I am glad to share some results with you:

```
result 0:
	 A person holding a white frisbee in their hand.
	 A man holding a frisbee in a park.
result 1:
	 A person standing in front of a television in a room.
	 A man standing in front of a television in a room.
result 2:
	 A person holding a pair of scissors in their hand.
	 A man holding a pair of scissors in a room.
result 3:
	 A person standing next to a large tree.
	 A man standing in front of a tree with a green umbrella.
result 4:
	 A group of people standing around a wooden bench.
	 A group of people standing around a wooden bench.
result 5:
	 A group of people sitting on top of a wooden bench.
	 A group of people sitting on a bench.
result 6:
	 A young boy is sitting on a bench with a camera.
	 A boy sitting on a bench with a laptop.
result 7:
	 A man in a suit and tie is standing in front of a window.
	 A man standing in front of a window in front of a window.
result 8:
	 A man standing in front of a wall holding a knife.
	 A man standing next to a wall holding a knife.
```

It can be seen that the reconstructed text has similar semantics to the original text.

**Comment by Adenialzz** [comment]
@fkodom @mbdzi  Extracting text features with the clip text encoder and reconstructing with the text decoder yielded plausible-looking results. Note that the text decoder is trained by the corresponding clip image encoder. I am glad to share some results with you:

```
result 0:
	 Origin Text: A person holding a white frisbee in their hand.
	 Rected Text: A man holding a frisbee in a park.
result 1:
	 Origin Text: A person standing in front of a television in a room.
	 Rected Text: A man standing in front of a television in a room.
result 2:
	 Origin Text: A person holding a pair of scissors in their hand.
	 Rected Text: A man holding a pair of scissors in a room.
result 3:
	 Origin Text: A person standing next to a large tree.
	 Rected Text: A man standing in front of a tree with a green umbrella.
result 4:
	 Origin Text: A group of people standing around a wooden bench.
	 Rected Text: A group of people standing around a wooden bench.
result 5:
	 Origin Text: A group of people sitting on top of a wooden bench.
	 Rected Text: A group of people sitting on a bench.
result 6:
	 Origin Text: A young boy is sitting on a bench with a camera.
	 Rected Text: A boy sitting on a bench with a laptop.
result 7:
	 Origin Text: A man in a suit and tie is standing in front of a window.
	 Rected Text: A man standing in front of a window in front of a window.
result 8:
	 Origin Text: A man standing in front of a wall holding a knife.
	 Rected Text: A man standing next to a wall holding a knife.
```

It can be seen that the reconstructed text has similar semantics to the original text. This is an interesting and plausible result and maybe we can do more things base on this.

**Comment by Adenialzz** [comment]
However, since the captions in the COCO dataset describe objective objects and their positional relationships, it may not be able to handle the reconstruction of conceptual texts. If there is training on concept captions, perhaps more generic results can be obtained, just like the TODO in the README said.

**Comment by mbdzi** [comment]
Great @Adenialzz! Are you at liberty to share the code that you used to do this? I have been stuck for weeks.

**Comment by Adenialzz** [comment]
> Great @Adenialzz! Are you at liberty to share the code that you used to do this? I have been stuck for weeks.

You can train a clip text decoder with this repo and refer to [this](https://github.com/Adenialzz/clip4aes/blob/main/tools/text_reconstruct.py).
